---
title: "Age over 90 years"
author: "Katarina Matthes"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Maps

```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_mapsPLZ_age(Year=1888, Place="Residential")
```

```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_mapsPLZ_age(Year=1900, Place="Residential")
```

<!-- Spatial prediction -->
<!-- ```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15} -->
<!-- function_spacial_age() -->
<!-- ``` -->

# Erhebungsjahr

<!-- * Poisson Regression -->
<!-- * Zwischen den Jahren 1888 und 1900 gibt es keinen signifikanten Unterschied zwischen der Anzahl der Ü90 Jährigen. -->

```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_language_diff(dataset="Original",Both ="yes")
```

# Geschlecht

## 1888

```{r echo=FALSE}
load("../data/data.obs.exp.sex.RData")
data.obs.exp.sex %>%
  filter(Year==1888) %>%
  mutate(Expected = round(Expected,0)) %>%
  select(Year,Sex,Population, Observed, Expected) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```


```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_sex_diff(YearM=1888)
```


## 1900

```{r echo=FALSE}
load("../data/data.obs.exp.sex.RData")
data.obs.exp.sex %>%
  filter(Year==1900) %>%
  mutate(Expected = round(Expected,0)) %>%
  select(Year,Sex,Population, Observed, Expected) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```


```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_sex_diff(YearM=1900)
```

# Urbanität

## 1888

```{r echo=FALSE}
load("../data/data.obs.exp.urbanity.RData")
data.obs.exp.urbanity %>%
  filter(Year==1888) %>%
  mutate(Expected = round(Expected,0)) %>%
  select(Year,Urbanity,Population, Observed, Expected) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```


```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_urbanity_diff(YearM=1888)
```


## 1900

```{r echo=FALSE}
load("../data/data.obs.exp.urbanity.RData")
data.obs.exp.urbanity %>%
  filter(Year==1900) %>%
  mutate(Expected = round(Expected,0)) %>%
  select(Year,Urbanity,Population, Observed, Expected) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```


```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_urbanity_diff(YearM=1900)
```

# Sprachregionen

<!-- * Poisson Regression -->
<!-- * Es gibt einen signifikanten Unterschied zwischen den Sprachregionen der Schweiz und dem Anteil Ü90 Jähriger. -->


<!-- * Da die Anzahl der Ü90 in 3 Datensätze unterschiedlich sind, habe ich die Regression auch noch für den UniGe Datensatz durchgeführt (dort weiss ich die Sprachregionen). -->

<!-- * Im Datensatz "AgeDistribution" habe ich nur die Altersverteilung der gesamten Schweiz, aber nicht nach Sprachregionen. -->
<!-- * Die Anzahl der Ü90 im AgeDistrubtion file erscheint mir verglichen zu dem "Original" Datensatz und dem UniGe Datensatz ein wenig zu hoch. -->
<!-- * Die Gesamtbevölkerung erscheint mir wiederrum im UniGe Datensatz zu niedrig -->
<!-- * Für die Berechnung des "Original" Datensatzes habe ich die beoachteten Werte aus dem Datensatz genommen und die Bevölkerung nach Sprachregionen aus dem Datensatz "Population_district_1860_2008.xlsx" (Ich weiss nicht, wo der herkommt. Habe ihn für mein UniGe Projekt benutzt) -->

<!-- * Für die UniGe Daten von 1888, sind alle Daten aus der Volkszählung -->


<!-- ## Tabelle  -->

<!-- ```{r echo=FALSE} -->
<!-- load("../data/data.obs.exp.language.RData") -->
<!-- data.obs.exp.language %>% -->
<!--   kbl() %>% -->
<!--   kable_material(c("striped", "hover"),full_width = F,position = "left") -->
<!-- ``` -->

## 1888

```{r echo=FALSE}
load("../data/data.obs.exp.language.RData")
data.obs.exp.language %>%
  filter(Year==1888) %>%
  mutate(Expected = round(Expected,0)) %>%
  select(Year,Language,Population = Pop, Observed, Expected) %>%
  mutate(Language = factor( Language, levels=c("German","French","Italian")))%>%
  arrange(Language) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```


```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_language_diff(dataset="Original", YearM=1888, Both="no")
```


## 1900

```{r echo=FALSE}
load("../data/data.obs.exp.language.RData")
data.obs.exp.language %>%
  filter(Year==1900) %>%
  mutate(Expected = round(Expected,0)) %>%
  select(Year,Language,Population = Pop, Observed, Expected) %>%
  mutate(Language = factor( Language, levels=c("German","French","Italian")))%>%
  arrange(Language) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```

<!-- * Poisson Regression -->
<!-- * Der Französische Teil und der Italienische Teil haben signifikant mehr Ü90 Jährige als der Deutschsprachige Teil -->

```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_language_diff(dataset="Original", YearM=1900, Both="no")
```

<!-- ## UniGe - 1888 -->
<!-- Das Ergebnis von den "Original" Daten kann mit den UniGe Daten bestätigt werden. -->
<!-- Der Französische Teil und der Italienische Teil haben signifikant mehr Ü90 Jährige als der Deutschsprachige Teil -->

<!-- ```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15} -->
<!-- function_language_diff(dataset="UniGe", YearM=1888, Both="no") -->
<!-- ``` -->


# Höhe Wohnort

## 1888

```{r echo=FALSE}
load("../data/data.obs.exp.altitude.RData")
data.obs.exp.altitude %>%
   filter(Year==1888) %>%
  mutate(Expected = round(Expected,0)) %>%
   select(Year,Altitude,Population, Observed, Expected) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```



<!-- * Poisson Regression -->
<!-- * Es leben auf allen Höhen mehr Ü90 Jährige verglichen zu den Wohnorten auf 400-599m. -->

```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_altitude_diff(YearM=1888)
```

## 1900

<!-- * Poisson Regression -->
<!-- * Es leben in den Wohnorten auf Höhe > 1000m signifikant mehr Ü90 Jährige verglichen zu den Wohnorten in der Höhe 400-599m. -->

```{r echo=FALSE}
load("../data/data.obs.exp.altitude.RData")
data.obs.exp.altitude %>%
   filter(Year==1900) %>%
  mutate(Expected = round(Expected,0)) %>%
   select(Year,Altitude,Population, Observed, Expected) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```

```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_altitude_diff(YearM=1900)
```

# Frauen und höhe Wohnort

## 1900

```{r echo=FALSE}
load("../data/data.obs.exp.altitude.female.RData")
data.obs.exp.altitude.female %>%
  mutate(Expected = round(Expected,0)) %>%
   select(Altitude,Population, Observed, Expected) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```


```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_altitude_female_diff()
```

# Männer und höhe Wohnort

## 1900

```{r echo=FALSE}
load("../data/data.obs.exp.altitude.male.RData")
data.obs.exp.altitude.male %>%
  mutate(Expected = round(Expected,0)) %>%
   select(Altitude,Population, Observed, Expected) %>%
  kbl() %>%
  kable_material(c("striped", "hover"),full_width = F,position = "left")
```


```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15}
function_altitude_male_diff()
```


<!-- # Regression Alter -->

<!-- * Gibt es Unterschiede in der Höhe des Sterbealters? Welche Faktoren beeinflussen die Höhe des Alters? -->

<!-- * Nur Daten mit einem Sterbealter -->
<!-- * Alle Modelle sind immer nach Erhebungsjahr kontrolliert -->


<!-- ```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15} -->
<!-- function_age_dead(Var="Year") -->
<!-- ``` -->

<!-- Sprachregionen: Es gibt keine signifikanten Unterschiede zwischen Sterbealter und den Sprachregionen -->
<!-- ```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15} -->
<!-- function_age_dead(Var="Language") -->
<!-- ``` -->

<!-- Wohnhöhe: Es gibt keine signifikanten Unterschiede zwischen Sterbealter und der Wohnhöhe -->
<!-- ```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15} -->
<!-- function_age_dead(Var="Altitude") -->
<!-- ``` -->

<!-- Wohnhöhe Kategorial: Es gibt keine signifikanten Unterschiede zwischen Sterbealter und der Wohnhöhe -->
<!-- ```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15} -->
<!-- function_age_dead(Var="Altitude_cat") -->
<!-- ``` -->

<!-- Interaktion Wohnhöhe + Sprachregion: Es gibt keine signifikanten Interaktionen zwischen Sterbealter, Wohnhöhe und Sprachregion -->
<!-- ```{r, echo=FALSE,message=FALSE,fig.height = 12,  fig.width = 15} -->
<!-- function_age_dead(Var="Altitude_Language") -->
<!-- ``` -->

